spring:
  application:
    name: EProducts
  datasource:
    url: jdbc:postgresql://localhost:5432/eproducts
    username: username
    password: username
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true